package cn.sunflyer.zfang;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;

import cn.sunflyer.zfang.obj.BandRanking;
import cn.sunflyer.zfang.obj.GradeInfo;
import cn.sunflyer.zfang.obj.UserInfo;

public class Saver {

	/**
	 * Print As Html
	 * */
	public static void saveGrade(UserInfo i) {
		saveGrade(GradeGrabber.getGrade(i),
				BandRankingGrabber.getBandRanking(i), "当前全部成绩 - " + i.no + " - "
						+ i.name);
	}

	public static void saveGrade(ArrayList<GradeInfo> p, UserInfo i) {
		saveGrade(p, null, "当前全部成绩 - " + i.no + " - " + i.name);
	}

	/**
	 * Print As Html
	 * */
	public static void saveGrade(ArrayList<GradeInfo> pGrade,
			ArrayList<BandRanking> pBand, String name) {
		File pFile = new File(name + ".html");
		if (!pFile.exists())
			try {
				pFile.createNewFile();
			} catch (IOException e1) {

				e1.printStackTrace();
				return;
			}

		StringBuffer pSb = new StringBuffer("<!DOCTYPE html><html><head>");
		// TODO : remove the following one line if webpage encoding failed.
		//pSb.append("<meta charset=\"UTF-8\">");

		pSb.append("<style>body{font-family:\"Microsoft Yahei\";text-align:center;}.conclusion{font-style:italic;color:purple;}.part_title{text-decoration:underline;}table{margin:auto;min-width:90%;}td{min-width:100px;}table{border:1px solid black;}.tr_head{background-color:#0043ff;color:white;}.tr_info{border-bottom:1px solid black;}.tr_back{background-color:#F0F0F0;}</style><title>"
				+ name + "</title></head><body><h2>" + name + "</h2>");

		boolean d = false;
		pSb.append("<p class=\"part_title\">Part I . 基本课程成绩信息</p>");
		if (pGrade != null) {
			pSb.append("<table><tr class=\"tr_head\"><td>学年</td><td>学期</td><td>课程性质</td><td>课程代码</td><td>课程名称</td><td>课程学分</td><td>绩点</td><td>成绩</td><td>重修标记</td></tr>");
			for (GradeInfo x : pGrade) {
				pSb.append("<tr class=\"tr_info" + (d ? " tr_back" : "")
						+ "\"><td>" + x.stuYear + "</td><td>" + x.stuPeriod
						+ "</td><td>" + x.classType + "</td><td>" + x.classCode
						+ "</td><td>" + x.className + "</td><td>" + x.credit
						+ "</td><td>" + x.point + "</td><td>" + x.grade
						+ "</td><td>" + x.noteSec + "</td></tr>");
				d = !d;
			}
			pSb.append("</table><p class=\"conclusion\">全科目平均绩点："
					+ String.format("%.2f", GradeGrabber.getGradePoint(pGrade))
					+ " , 除体育和公共选修课外平均绩点："
					+ String.format("%.2f",
							GradeGrabber.getGradePointNoPE(pGrade)) + "</p>");
		} else {
			pSb.append("课程成绩查询：没有查询到课程成绩");
		}

		d = false;
		// 等级考试信息开始
		pSb.append("<p class=\"part_title\">Part II . 等级考试成绩信息</p>");
		if(pBand != null){
			pSb.append("<table><tr class=\"tr_head\"><td>学年</td><td>学期</td><td>等级考试名称</td><td>准考证号</td><td>成绩</td></tr>");
			for(BandRanking x : pBand){
				pSb.append("<tr class=\"tr_info" + (d ? " tr_back" : "") + "\"><td>" + x.stuYear  + "</td><td>" + x.stuPeriod + "</td><td>" + x.bandName + "</td><td>" + x.accessId + "</td><td>" + x.score + "</td></tr>");
				d=!d;
			}
			pSb.append("</table>");
		}else{
			pSb.append("等级考试查询：没有查询到数据");
		}
		
		pSb.append("<p>Automatic Generated By CQUTEduSystemGrabber @ "
				+ ((new Date()).toString())
				+ " <a href=\"https://github.com/sunflyer/CQUTEduSystemGrabber\">GitHub</a></p></body></html>");
		try {
			FileWriter pW = new FileWriter(pFile);
			pW.write(pSb.toString());
			pW.close();
			Runtime.getRuntime().exec("explorer " + name + ".html");

		} catch (IOException e) {

			e.printStackTrace();
		}

	}

}
